"""Test stubs for clarify prompts (no private content)."""

ASSESS_GOAL_SYSTEM = "STUB clarify.ASSESS_GOAL_SYSTEM"
ASSESS_GOAL_CAP_REACHED = "STUB clarify.ASSESS_GOAL_CAP_REACHED"
GENERATE_QUESTIONS_SYSTEM = "STUB clarify.GENERATE_QUESTIONS_SYSTEM"
REFINE_GOAL_SYSTEM = "STUB clarify.REFINE_GOAL_SYSTEM"
