"""Test stubs for material prompts (no private content)."""

PLAN_SLIDE_CONTENTS_SYSTEM = "STUB material.PLAN_SLIDE_CONTENTS_SYSTEM"
SUMMARIZE_STEP_SYSTEM = "STUB material.SUMMARIZE_STEP_SYSTEM"
WRITE_QUESTIONS_SYSTEM = "STUB material.WRITE_QUESTIONS_SYSTEM"
_JSX_SYSTEM_PROMPT = "STUB material._JSX_SYSTEM_PROMPT"
_PLACEHOLDER_JSX_TEMPLATE = "STUB material._PLACEHOLDER_JSX_TEMPLATE"
