"""Test stubs for plan prompts (no private content)."""

RESEARCH_TOPIC_SYSTEM = "STUB plan.RESEARCH_TOPIC_SYSTEM"
DESIGN_PLAN_INITIAL_SYSTEM = "STUB plan.DESIGN_PLAN_INITIAL_SYSTEM"
DESIGN_PLAN_REFINE_SYSTEM = "STUB plan.DESIGN_PLAN_REFINE_SYSTEM"
RENDER_PLAN_SYSTEM = "STUB plan.RENDER_PLAN_SYSTEM"
